### ISSUE TITLE
[BUG] Token can not create, error when trying to receive a new token

### ISSUE THREAD

**Issue by ngrujicic** [MVPWorkshop/dot-acp-ui#268] opened 2023-10-13 14:52 UTC
You can not receive new tokens if you have 16 assets/tokens already on your account.

We need to show to the user a warning message telling him that he has too many assets on his account.

Important note: we need to check if this is something that is happening only on the test networks.

**Comment by Kouteki** [comment] 2023-10-16 07:13
Duplicate of #215

**Closed as completed** 2023-11-27 11:02 UTC
Labels: bug, medium
